name: Check Markdown links

on:
  push:
    branches:
      - master
  schedule:
    # Run every Monday at 8:00 AM (CST)
    - cron: "0 12 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
